EShope/Entities/Account/User.cs
using EShope.Entities.Common;
using System.ComponentModel.DataAnnotations;

namespace EShope.Entities.Account
{
    public class User : BaseEntity
    {
        [MaxLength(150)]
        public string Email { get; set; }

        [MaxLength(300)]
        public string? EmailActiveCode { get; set; }

        [MaxLength(200)]
        public string Password { get; set; }

        [MaxLength(150)]
        public string? FirstName { get; set; }

        [MaxLength(150)]
        public string? LastName { get; set; }

        [MaxLength(500)]
        public string Address { get; set; }

        public DateTime RegisterDate { get; set; }

        public DateTime? LastLoginDate { get; set; }

        //The is bool Type is Defaultly Is false And No Need to be Nullable
        public bool IsActive { get; set; }
    }
}

EShope/Entities/Blog/Article.cs
using EShope.Entities.Common;
using System.ComponentModel.DataAnnotations;

namespace EShope.Entities.Blog
{
    public class Article :BaseEntity
    {

        [MaxLength(300)]
        public string Title { get; set; }

        public string Text { get; set; }

        [MaxLength(2000)]
        public string? Tags { get; set; }

        [MaxLength(300)]
        public string Image { get; set; }

        public bool Published { get; set; }

        public DateTime CreateDate { get; set; }

        public bool Deleted { get; set; }

    }
}

EShope/Entities/Catalog/Banner.cs
using EShope.Entities.Common;
using System.ComponentModel.DataAnnotations;

namespace EShope.Entities.Catalog
{
    public class Banner:BaseEntity
    {


        [MaxLength(200)]
        public string Title { get; set; }

        [MaxLength(300)]
        public string Image { get; set; }

        [MaxLength(500)]
        public string Url { get; set; }

        [MaxLength(300)]
        public string UrlTitle { get; set; }

        [MaxLength(1000)]
        public string? Text { get; set; }

        public int DisplayOrder { get; set; }

        [MaxLength(100)]
        public string Position { get; set; }

    }
}

EShope/Entities/Common/BaseEntity.cs
using System.ComponentModel.DataAnnotations;

namespace EShope.Entities.Common
{


    //I Add abstract Phrese Bitwin public & class
    public abstract class BaseEntity
    {
        [Key]
        public int Id { get; set; }
    }
}

EShope/ViewModels/Account/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace EShope.ViewModels.Account
{
    public class RegisterViewModel
    {
       


        [Display(Name ="ایمیل")]
        [Required(ErrorMessage ="لطفا {0} را وارد نمایید")]
        [EmailAddress(ErrorMessage ="آدرس ایمیل وارد شده معتبر نمی باشد")]
        [MaxLength(150,ErrorMessage ="طول عبارت وارد شده نباید بیشتر از {1} کاراکتر باشد")]
        public string Email { get; set; }

        [Display(Name = "پسورد")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "لطفا {0} را وارد نمایید")]
        [MaxLength(20, ErrorMessage = "طول {0} وارد شده نباید بیشتر از {1} کاراکتر باشد")]
        public string Password { get; set; }

        [Display(Name = "پسورد")]
        [Required(ErrorMessage = "لطفا {0} را وارد نمایید")]
        [MaxLength(20, ErrorMessage = "طول تکرار {0} وارد شده نباید بیشتر از {1} کاراکتر باشد")]
        [DataType(DataType.Password)]
        [Compare("Password",ErrorMessage ="تکرار {0} نادرست است")]
        public string ConfirmPassword { get; set; }

    }
}

EShope/Controllers/AccountController.cs
using EShope.ViewModels.Account;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;

namespace EShope.Controllers
{
    public class AccountController : Controller

    {
        // [Route("register")]   //برای آدرس دستی دادن به دلخواه

        [HttpGet("register")] //اگر بخواهیم بگوییم براساس نوع متد که get یا post باشد اجرا شود وآدرس دلبخواه بدهیم
        public IActionResult Register()
        {
            return View();
        }



        /*
         *  پارامتر فیلد ثبت نام را میتوان بدون ایجاد کردن ویو مدل مستقیما به این صورت دریافت کرد ولی اصولی نیست 
         *  زیرا هیچ کنترل و اعتبار سنجی سمت سرور روی این فیلد ها نخواهیم داشت و کاربر حتی می تواند دیتا اینجکشن انجام دهد
         * در پایین به صورت اصولی و با استفاده از ویو مدل پیاده سازی شده
       

        [HttpPost("register")]
        public IActionResult Register(string email,string password,string confirmPassword) 
        {
            return View();
        }
        */

        [HttpPost("register")]
        public IActionResult Register(RegisterViewModel register)
        {
            if (ModelState.IsValid)
            {
              
            }
            else
            {


            }
            return View();
        }


    }
}

EShope/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;


namespace EShope.Controllers;



//=======>>View Data And View bag example<===========


//public class HomeController : Controller
//{
//    private List<string> Products = new List<string>
//    {
//        "Laptop",
//        "Smartphone",
//        "Tablet",
//        "Smartwatch"
//    };
//    private readonly ILogger<HomeController> _logger;

//    public HomeController(ILogger<HomeController> logger)
//    {
//        _logger = logger;
//    }
//    public IActionResult Index()
//    {
//        ViewBag.Products = Products;
//        ViewData["Products"] = Products;
//        return View ();
//    }

//    public IActionResult Privacy()
//    {
//        return View();
//    }


//}




public class HomeController : Controller
{


    public IActionResult Index()
    {
        //ViewBag.Products = Products;
        //ViewData["Products"] = Products;
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }


}

EShope/ViewComponents/MainSliderViewComponent.cs
using EShope.Contex;
using Microsoft.AspNetCore.Mvc;

namespace EShope.ViewComponents
{
    public class MainSliderViewComponent:ViewComponent
    {

        private ApplicationDbContext _context;

        public MainSliderViewComponent(ApplicationDbContext context)
        {
            _context = context;
        }












public  IViewComponentResult Invoke()
        {

            var banner = _context.Banners.ToList();
            return View("MainSlider",banner);

        }

    }
}

EShope/ViewComponents/SiteFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace EShope.ViewComponents
{
    public class SiteFooterViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("SiteFooter");
        }
    }
}

EShope/ViewComponents/SiteHeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace EShope.ViewComponents
{
    public class SiteHeaderViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View("SiteHeader");
        }
    }
}

EShope/Views/Shared/Components/MainSlider/MainSlider.cshtml
@using EShope.Entities.Catalog



@model List<Banner>
@{
    int Index = 0;
}


<section id="slider">
    <!--slider-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div id="slider-carousel" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                       
                        @for(int i=0;i<Model.Count; i++)
                        {
                            <li data-target="#slider-carousel" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
                        }
                    </ol>

                    <div class="carousel-inner">
                        @foreach (var banner in Model)
                        {
                            <div class="item @(Index == 0 ? "active" : "")">
                                <div class="col-sm-6">
                                    <h1><span>SHOP</span>CENTER</h1>
                                    <h2>@banner.Title</h2>
                                    <p>@banner.Text </p>
                                    <a href="@banner.Url" class="btn btn-default get">@banner.UrlTitle</a>
                                </div>
                                <div class="col-sm-6">
                                    <img src="@banner.Image" class="girl img-responsive" alt="" />
                                    <img src="/Site/images/home/pricing.png" class="pricing" alt="" />
                                </div>


                            </div>


                            Index++;
                        }


                    </div>

                    <a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
                        <i class="fa fa-angle-left"></i>
                    </a>
                    <a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
                        <i class="fa fa-angle-right"></i>
                    </a>
                </div>

            </div>
        </div>
    </div>
</section><!--/slider-->

EShope/Views/Shared/Components/SiteFooter/SiteFooter.cshtml
<footer id="footer">
	<!--Footer-->
	<div class="footer-Before">
		<div class="container">
			<div class="block-news">
				<div class="row">
					<h3>با عضویت در خبـرنامه ما از تخفیفات ویـژه ما با خبـر شوید ... </h3>
					<div class="searchform newslatter">
						<input type="text" placeholder="آدرس ایمیـل شما ..." />
						<button type="submit" class="btn btn-default">
							<i class="fa fa-arrow-circle-o-left"></i>
						</button>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-top">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="address">
						<img src="/Site/images/home/map.png" alt="" />
					</div>
				</div>
				<div class="col-sm-3">
					<div class="address">
						<img src="/Site/images/home/map.png" alt="" />
					</div>
				</div>
				<div class="col-sm-6">
					<div class="companyinfo">
						<h2><span>SHOP</span>CENTER</h2>
						<h4>درباره ما :</h4>
						<p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده ازلورملورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. کتابهای زیادی در شصت و سه درصد گذشته، حال و آینده شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد.</p>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-widget">
		<div class="container">
			<div class="row">
				<div class="col-sm-3">
					<div class="single-widget">
						<h2>Service</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Online Help</a></li>
							<li><a href="#">Contact Us</a></li>
							<li><a href="#">Order Status</a></li>
							<li><a href="#">Change Location</a></li>
							<li><a href="#">FAQ’s</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="single-widget">
						<h2>Quock Shop</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">T-Shirt</a></li>
							<li><a href="#">Mens</a></li>
							<li><a href="#">Womens</a></li>
							<li><a href="#">Gift Cards</a></li>
							<li><a href="#">Shoes</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="single-widget">
						<h2>Policies</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Terms of Use</a></li>
							<li><a href="#">Privecy Policy</a></li>
							<li><a href="#">Refund Policy</a></li>
							<li><a href="#">Billing System</a></li>
							<li><a href="#">Ticket System</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-3">
					<div class="single-widget">
						<h2>About Shopper</h2>
						<ul class="nav nav-pills nav-stacked">
							<li><a href="#">Company Information</a></li>
							<li><a href="#">Careers</a></li>
							<li><a href="#">Store Location</a></li>
							<li><a href="#">Affillate Program</a></li>
							<li><a href="#">Copyright</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="footer-bottom" style="direction: ltr !important;">
		<div class="container">
			<div class="row">
				<p class="pull-left">
					Copyright © 2018
					<a target="_blank" href="http://www.1614GP.ir"><b>1614Group</b></a>. All rights reserved.
				</p>
			</div>
		</div>
	</div>

</footer><!--/Footer-->

EShope/Views/Shared/Components/SiteHeader/SiteHeader.cshtml
<header id="header">
	<!--header-->
	<div class="header_top">
		<!--header_top-->
		<div class="container">
			<div class="row">
				<div class="col-sm-6">
					<div class="contactinfo">
						<ul class="nav nav-pills">
							<li><a href="#"><i class="fa fa-phone"></i> 80 21 24 36 98+ </a></li>
							<li><a href="#"><i class="fa fa-envelope"></i> info@domain.com</a></li>
						</ul>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="social-icons pull-right">
						<ul class="nav navbar-nav">
							<li><a href="#"><i class="fa fa-facebook"></i></a></li>
							<li><a href="#"><i class="fa fa-twitter"></i></a></li>
							<li><a href="#"><i class="fa fa-linkedin"></i></a></li>
							<li><a href="#"><i class="fa fa-dribbble"></i></a></li>
							<li><a href="#"><i class="fa fa-google-plus"></i></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div><!--/header_top-->

	<div class="header-middle">
		<!--header-middle-->
		<div class="container">
			<div class="row">
				<!-- <div class="col-sm-4 header-middle-menu">
					<div class="shop-menu pull-left">
						<ul class="nav navbar-nav">
							<li><a href="checkout.html"><i class="fa fa-crosshairs"></i> پرداخت</a></li>
						</ul>
					</div>
				</div> -->

				<div class="col-sm-4" style="text-align: left;">
					<div class="logo">
						<a href="index.html"><img src="/Site/images/home/logo.png" alt="Logo" style="text-align: center;" /></a>
					</div>
				</div>

				<div class="col-sm-8 header-middle-menu">
					<div class="shop-menu pull-right">
						<ul class="nav navbar-nav">
							<li><a href="#"><i class="fa fa-user"></i> حساب کاربـری</a></li>
							<li><a href="#"><i class="fa fa-star"></i> لیست علاقه مندی ها</a></li>
							<li><a href="login.html"><i class="fa fa-lock"></i> ورود</a></li>
							<li><a href="cart.html"><i class="fa fa-shopping-cart"></i> سبد خریـد</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div><!--/header-middle-->

	<div class="header-bottom">
		<!--header-bottom-->
		<div class="container">
			<div class="row">

				<div class="col-sm-3">
					<div class="search_box pull-left">
						<input type="text" placeholder="جستـجو" />
					</div>
				</div>

				<div class="col-sm-9">
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
					</div>
					<div class="mainmenu pull-right">
						<ul class="nav navbar-nav collapse navbar-collapse">
							<li><a href="index.html" class="active">خـانه</a></li>
							<li class="dropdown">
								<a href="#">فروشگـاه<i class="fa fa-angle-down"></i></a>
								<ul role="menu" class="sub-menu">
									<li><a href="shop.html">محصولات</a></li>
									<li><a href="product-details.html">جزئیات محصولات</a></li>
									<li><a href="checkout.html">پرداخت</a></li>
									<li><a href="cart.html">سبـد خریـد</a></li>
									<li><a href="login.html">ورود</a></li>
								</ul>
							</li>
							<li class="dropdown">
								<a href="#">اخبـار<i class="fa fa-angle-down"></i></a>
								<ul role="menu" class="sub-menu">
									<li><a href="blog.html">آخریـن اخبـار</a></li>
									<li><a href="blog-single.html">صفحـه خبـر</a></li>
								</ul>
							</li>
							<li><a href="About.html">درباره مـا</a></li>
							<li><a href="contact-us.html">تماس با مـا</a></li>
						</ul>
					</div>
				</div>

			</div>
		</div>
	</div><!--/header-bottom-->
</header><!--/header-->

EShope/Views/Shared/_FooterReferencesPartial.cshtml
<script src="/Site/js/jquery.js"></script>
<script src="/Site/js/bootstrap.min.js"></script>
<script src="/Site/js/jquery.scrollUp.min.js"></script>
<script src="/Site/js/price-range.js"></script>
<script src="/Site/js/jquery.prettyPhoto.js"></script>
<script src="/Site/js/main.js"></script>

EShope/Views/Shared/_HeadReferencesPartial.cshtml
<link href="/Site/css/bootstrap.min.css" rel="stylesheet">
<link href="/Site/css/font-awesome.min.css" rel="stylesheet">
<link href="/Site/css/prettyPhoto.css" rel="stylesheet">
<link href="/Site/css/price-range.css" rel="stylesheet">
<link href="/Site/css/animate.css" rel="stylesheet">
<link href="/Site/css/main.css" rel="stylesheet">
<link href="/Site/css/responsive.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="/Site/js/html5shiv.js"></script>
<script src="/Site/js/respond.min.js"></script>
<![endif]-->
<link rel="shortcut icon" href="/Site/images/ico/favicon.ico">
<link rel="apple-touch-icon-precomposed" sizes="144x144" href="/Site/images/ico/apple-touch-icon-144-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="114x114" href="/Site/images/ico/apple-touch-icon-114-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="72x72" href="/Site/images/ico/apple-touch-icon-72-precomposed.png">
<link rel="apple-touch-icon-precomposed" href="/Site/images/ico/apple-touch-icon-57-precomposed.png">

EShope/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">
	<title>صفحه اصلی | فروشگاه کارزیبا</title>
</head><!--/head-->


<body>
	<partial name="_HeadReferencesPartial" />
	@await Component.InvokeAsync("SiteHeader");
	@RenderBody();
	@await Component.InvokeAsync("SiteFooter");
	<partial name="_FooterReferencesPartial" />
	@RenderSection("ExtraScripts", false);
</body>
</html>